python simul.py --algo prema --batch 1 --num 4
python simul.py --algo prema --batch 1 --num 4
python simul.py --algo fcfs --batch 1 --num 4
python simul.py --algo fcfs --batch 1 --num 4
python simul.py --algo rrb --batch 1 --num 4
python simul.py --algo rrb --batch 1 --num 4
python simul.py --algo hpf --batch 1 --num 4
python simul.py --algo hpf --batch 1 --num 4
python simul.py --algo token --batch 1 --num 4
python simul.py --algo token --batch 1 --num 4
python simul.py --algo sjf --batch 1 --num 4
python simul.py --algo sjf --batch 1 --num 4
python simul.py --algo prema --batch 4 --num 4
python simul.py --algo prema --batch 4 --num 4
python simul.py --algo fcfs --batch 4 --num 4
python simul.py --algo fcfs --batch 4 --num 4
python simul.py --algo rrb --batch 4 --num 4
python simul.py --algo rrb --batch 4 --num 4
python simul.py --algo hpf --batch 4 --num 4
python simul.py --algo hpf --batch 4 --num 4
python simul.py --algo token --batch 4 --num 4
python simul.py --algo token --batch 4 --num 4
python simul.py --algo sjf --batch 4 --num 4
python simul.py --algo sjf --batch 4 --num 4
python simul.py --algo prema --batch 1 --num 8
python simul.py --algo prema --batch 1 --num 8
python simul.py --algo fcfs --batch 1 --num 8
python simul.py --algo fcfs --batch 1 --num 8
python simul.py --algo rrb --batch 1 --num 8
python simul.py --algo rrb --batch 1 --num 8
python simul.py --algo hpf --batch 1 --num 8
python simul.py --algo hpf --batch 1 --num 8
python simul.py --algo token --batch 1 --num 8
python simul.py --algo token --batch 1 --num 8
python simul.py --algo sjf --batch 1 --num 8
python simul.py --algo sjf --batch 1 --num 8
python simul.py --algo prema --batch 4 --num 8
python simul.py --algo prema --batch 4 --num 8
python simul.py --algo fcfs --batch 4 --num 8
python simul.py --algo fcfs --batch 4 --num 8
python simul.py --algo rrb --batch 4 --num 8
python simul.py --algo rrb --batch 4 --num 8
python simul.py --algo hpf --batch 4 --num 8
python simul.py --algo hpf --batch 4 --num 8
python simul.py --algo token --batch 4 --num 8
python simul.py --algo token --batch 4 --num 8
python simul.py --algo sjf --batch 4 --num 8
python simul.py --algo sjf --batch 4 --num 8
